#version 450 core

layout (local_size_x=1) in;


layout(set=0,binding=0) buffer  inDat{
    mat3 data[];
} inInt;

layout(set=0,binding=1)buffer  Time {
    float val[];
}time;


void main(){
    uint glID = gl_GlobalInvocationID.x;
        if(glID <= 1){


        for(int i=1;i<100;i++){
           inInt.data[i] = mat3(1,1,1,
                                2,2,2,
                                3,3,3);
        }


    }

}